#!/usr/bin/env node
/**
 * Repository link hygiene check.
 *
 * Every repository link in the project must point at the canonical
 * "mheci/Orbis" location: owner and repository are pinned so a renamed
 * account or repo can never silently break clone URLs, badges, issue
 * links or vulnerability-reporting paths.
 *
 * This runs in CI and fails the build if a link to any other location
 * appears in the scanned files.
 */

import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';

const CANONICAL_OWNER = 'mheci';
const CANONICAL_REPO = 'Orbis';

const SCAN_EXTENSIONS = new Set(['.md', '.json', '.yml', '.yaml', '.ts', '.mjs', '.js', '.html']);
const SKIP_DIRS = new Set([
  'node_modules',
  'dist',
  'coverage',
  'web-ext-artifacts',
  '.git',
  '.github/cache',
]);
// package-lock.json records third-party funding and sponsor links and is
// generated by the package manager; it is not a source of repo links.
const SKIP_FILES = new Set(['package-lock.json']);

const GITHUB_LINK = /github\.com[/:]([a-zA-Z0-9-]+)(?:\/([a-zA-Z0-9._-]+))?/g;
const GITHUB_IO = /@([a-zA-Z0-9-]+)\.github\.io/g;

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') && entry.name !== '.github') continue;
    if (SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else if (SCAN_EXTENSIONS.has(path.extname(entry.name)) && !SKIP_FILES.has(entry.name)) {
      out.push(full);
    }
  }
  return out;
}

const errors = [];
const files = await walk('.');

for (const file of files) {
  const content = await readFile(file, 'utf8');
  const lines = content.split('\n');
  lines.forEach((line, index) => {
    const stripped = line.replace(/`[^`]*`/g, '');
    for (const match of stripped.matchAll(GITHUB_LINK)) {
      const owner = match[1].replace(/\.git$/, '');
      const repo = match[2] ? match[2].replace(/\.git$/, '') : null;
      if (owner !== CANONICAL_OWNER || (repo !== null && repo !== CANONICAL_REPO)) {
        errors.push(
          `${file}:${index + 1} links to "${match[0]}" — use "${CANONICAL_OWNER}/${CANONICAL_REPO}"\n      ${line.trim().slice(0, 120)}`
        );
      }
    }
    for (const match of stripped.matchAll(GITHUB_IO)) {
      if (match[1] !== CANONICAL_OWNER) {
        errors.push(
          `${file}:${index + 1} links to "@${match[1]}.github.io" — use "@${CANONICAL_OWNER}.github.io"\n      ${line.trim().slice(0, 120)}`
        );
      }
    }
  });
}

// Canonical owner/repo must actually be present, otherwise check would vacuously pass
const readme = await readFile('README.md', 'utf8');
if (!readme.includes(`github.com/${CANONICAL_OWNER}/${CANONICAL_REPO}`)) {
  errors.push(`README.md does not link to github.com/${CANONICAL_OWNER}/${CANONICAL_REPO}`);
}

if (errors.length > 0) {
  console.error('[links] repository link check failed:');
  for (const error of errors) console.error(`  - ${error}`);
  process.exit(1);
}
console.log(
  `[links] ${files.length} files scanned, all repository links point at "${CANONICAL_OWNER}/${CANONICAL_REPO}"`
);
