#!/usr/bin/env node
/**
 * Remove build output.
 *
 * `dist/` is fully regenerated by every build, so it is wiped outright.
 *
 * `web-ext-artifacts/` is treated more carefully: signed `.xpi` files are
 * obtained from Mozilla's signing service and cannot be recreated locally, so
 * blowing them away on an ordinary `npm run build` loses work that takes
 * minutes to get back. Only the locally reproducible `.zip` archives are
 * removed. Pass `--all` to clear signed artifacts too.
 */
import { readdir, rm } from 'node:fs/promises';
import path from 'node:path';

const removeAll = process.argv.includes('--all');

await rm('dist', { recursive: true, force: true });

let keptSigned = 0;
try {
  for (const entry of await readdir('web-ext-artifacts', { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const isSigned = entry.name.endsWith('.xpi');
    if (isSigned && !removeAll) {
      keptSigned++;
      continue;
    }
    await rm(path.join('web-ext-artifacts', entry.name), { force: true });
  }
} catch {
  // Directory does not exist yet — nothing to clean.
}

const note =
  keptSigned > 0 ? ` (kept ${keptSigned} signed .xpi; use "npm run clean -- --all" to remove)` : '';
console.log(`[clean] removed dist/ and unsigned artifacts${note}`);
